---
title: "Dplyr"
author: "Jairo Nicolau"
date: "8/18/2020"
output: html_document
---

### Carregando o banco


```{r}
library(tidyverse) 

gapminder <- read.csv ("gapminder.csv")
```

```{r}
glimpse(gapminder)
```

### Operador pipe

CONTROL + SHIFT + M

```{r}
gapminder %>% glimpse 
```


### *Filter*  para filtrar linhas

```{r}
gapminder %>% 
  filter (lifeExp > 35) 
```

```{r}
gapminder %>% 
  filter (country == "Argentina", year >= 1992)
```
```{r}
gapminder %>% 
  filter (country %in% c("Rwanda", "Afghanistan", "Brazil"))
```

### *Select* para selecionar colunas

```{r}
gapminder %>%
  select(year, lifeExp, continent) 
```


```{r}
gapminder %>%
  filter(country == "Brazil") %>%
  select(year, lifeExp) 
```


### *Mutate* para criar uma nova variável


```{r}
gapminder %>%
  mutate(pib = pop * gdpPercap)  %>% 
  select(pib)
```

### *Arrange* para ordenar por uma variável


```{r}
gapminder %>%
  arrange(year, lifeExp)
```



```{r}
gapminder  %>%
  filter(year == 2007) %>%
  arrange(desc(lifeExp)) %>% 
  select(country, lifeExp) %>% 

```

### *Rename* para renomear as variáveis

```{r}
gapminder %>%
  rename(expectativa_vida = lifeExp,
         gdp_percap = gdpPercap,
         continente = continent)
```

### *Groupby* + *Summarize*


#### Contando

```{r}
gapminder %>%
  group_by(continent) %>%
  summarize(observacoes = n())
```


```{r}
gapminder %>%
  group_by(continent) %>%
  summarize(n = n(),
            ano = n_distinct(year))
```

#### Sumarização geral


mean(), median(), var(), sd(), mad(), IQR(), min(), and max()

```{r}
gapminder %>%
  #filter(year==2007) %>% 
  group_by(country) %>%
  summarize(median_lifeExp = median(lifeExp)) %>% 
  arrange(desc(median_lifeExp))
```

```{r}
gapminder %>%
  filter(continent == "Asia") %>%
  group_by(year) %>%
  summarize(min_lifeExp = min(lifeExp), max_lifeExp = max(lifeExp))
```






