---
title: "Gráficos para apresentação"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Tamanho da fonte

```{r}
library(tidyverse) 
library(ggthemes)
```



```{r}
data(Salaries, package="carData")
```

## Refinando a aparesentação

```{r}
ggplot(Salaries, 
       aes(x = yrs.since.phd, 
           y = salary)) +
  geom_point()
```

## Mudando o tema, a cor, a intensidade da cor e o tamanho da esfera

```{r}
ggplot(Salaries, 
       aes(x = yrs.since.phd, 
           y = salary)) +
  geom_point(color="cornflowerblue", 
             size = 3, 
             alpha=.7) +
  #theme_minimal() +
  theme_light() +
  
  scale_y_continuous(label = scales::dollar, 
                     limits = c(50000, 250000)) +
  scale_x_continuous(breaks = seq(0, 60, 10), 
                     limits=c(0, 60)) + 
  labs(x = "Anos desde o começo do Doutorado",
       y = "",
       title = "Experiência vs. Salário",
       subtitle = "Salário para 2008-2009")
#ggsave("figura1.pdf") 
```

### salvando em pdf com tamanho maior 

```{r}
ggplot(Salaries, 
       aes(x = yrs.since.phd, 
           y = salary)) +
  geom_point(color="cornflowerblue", 
             size = 3, 
             alpha=.7) +
  #theme_minimal() +
  theme_light(base_size = 14) +
  
  scale_y_continuous(label = scales::dollar, 
                     limits = c(50000, 250000)) +
  scale_x_continuous(breaks = seq(0, 60, 10), 
                     limits=c(0, 60)) + 
  labs(x = "Anos desde o começo do Doutorado",
       y = "",
       title = "Experiência vs. Salário",
       subtitle = "Salário para 2008-2009")
ggsave("figura1.pdf") 
```


### salvando em png


```{r}
ggplot(Salaries, 
       aes(x = yrs.since.phd, 
           y = salary)) +
  geom_point(color="cornflowerblue", 
             size = 3, 
             alpha=.7) +
  #theme_minimal() +
  theme_light(base_size = 14) +
  
  scale_y_continuous(label = scales::dollar, 
                     limits = c(50000, 250000)) +
  scale_x_continuous(breaks = seq(0, 60, 10), 
                     limits=c(0, 60)) + 
  labs(x = "Anos desde o começo do Doutorado",
       y = "",
       title = "Experiência vs. Salário",
       subtitle = "Salário para 2008-2009")

ggsave("figura2.png") 
```


### Banco do trabalho final (grupos 1 e 2) 

```{r}
df <- read_csv2("bairros_rio_eleicao_2008.csv")
```

